### ISSUE TITLE
Suggestion: Make only custom titles visible

### ISSUE THREAD

**Issue by iv230** [yomishino/FFXIVTitleRenamed#1]
To reduce the amount of information displayed on my screen I disabled titeles visibility. But I'm interested to see my freinds custom titeles through Mare Synchronos. I so suggest an option to make all vanilla titles not visible above other players head (or replace them by empty string?) and display only the ones that are custom!

**Comment by yomishino** [comment]
Thanks for the suggestion. I am not familiar with Mare Synchronos, so not sure if it is possible to distinguish custom titles from the vanilla ones. Does that plugin allow you to set up custom title by tweaking some native functions in the game client or by adding an additional layer to display whatever new information provided by that plugin (including custom titles), for instance? 

Or in less technical terms, if you turned off displaying any arbitrary titles in my plugin, can all the custom titles show up on the screen? If so I can add an option to turn off displaying all titles built-in in the game client, and see if that may be the feature you are looking for.

**Comment by iv230** [comment]
For any reason, that I'm still not able to understand, I consufed your plugin with Honorific. I'm almost sure I clicked on "Got o webstine" from plugin installer but loos like I did not. So... it apperas that I never tested your plugin event if I'm intersted now and will have a look on it. I'm very sorry for the confusion!
